$(NAME)_pub.zip: $(ZIP_PUB_CONTENTS)
	rm -f $@
	zip $@ $(ZIP_PUB_CONTENTS)

$(NAME).zip: $(ZIP_CONTENTS)
	rm -f $@
	zip $@ $(ZIP_CONTENTS)

$(NAME)_local.zip: $(ZIP_LOCAL_CONTENTS)
	rm -f $@
	zip $@ $(ZIP_LOCAL_CONTENTS)

.PHONY: clean

clean:
	rm -f $(DOCUMENTS) $(ZIPS)
	rm -f $(addprefix pub/, $(SOURCES))
	find -iname '*.run.xml' -exec rm -f \{\} \;
	find -iname '*.aux' -exec rm -f \{\} \;
	find -iname '*.bgl' -exec rm -f \{\} \;
	find -iname '*.blg' -exec rm -f \{\} \;
	find -iname '*.bcf' -exec rm -f \{\} \;
	find -iname '*.bbl' -exec rm -f \{\} \;
	find -iname '*.out' -exec rm -f \{\} \;
	find -iname '*.log' -exec rm -f \{\} \;
	find -iname '*.toc' -exec rm -f \{\} \;

.PHONY: escape-accented-chars

escape-accented-chars:
	find -iname '*.tex' -exec sed -i 's/ё/\\"е/g' \{\} \;
	sed -i 's/ё/\\"е/g' $(NAME).tex

# ----
# Local build
# ----


$(NAME).pdf: $(SOURCES) $(NAME).bbl
	$(LTEX) $(NAME).tex
	$(LTEX) $(NAME).tex
	touch $@

%.bbl: %.tex %.bib
	$(LTEX) $*.tex
	$(LBIB) $*
	touch $@

%.pdf: %.toc %.tex
	$(LTEX) *.tex
	$(LTEX) *.tex
	touch $@

%.toc: %.tex
	$(LTEX) $*.tex
	touch $@

# ----
# Composing publishable output
# ----

pub:
	mkdir pub

# You can override a source file
# for the publishable version
# by creating a pub_* substitute file
pub/%.tex: pub_%.tex pub
	@mkdir -p $(shell dirname $@)
	iconv -f utf8 -t $(OUTENC) $< -o $@

pub/%: pub_% pub
	cp -f $< $@

pub/authors.pdf: authors.pdf | pub
	cp -f $< $@

# If there's no pub_% file
# but there's %, then it'll be
# `iconv`-ed to $(OUTENC), e.g. cp1251.
# This is useful for .tex files
pub/%.tex: %.tex pub
	@echo : Making $@
	@mkdir -p $(shell dirname $@)
	iconv -f utf8 -t $(OUTENC) $< -o $@

pub/%.bib: %.bib pub
	@echo : Making $@
	@mkdir -p $(shell dirname $@)
	iconv -f utf8 -t $(OUTENC) $< -o $@

pub/$(NAME).pdf: pub/$(NAME).toc $(PUB_SOURCES) pub/$(NAME).bbl
	@echo : Making $@
	cd pub ; $(PTEX) $(NAME).tex
	cd pub ; $(PTEX) $(NAME).tex
	touch $@

pub/%.bbl: pub/%.tex pub/%.bib
	echo Making $@
	cd pub ; $(PTEX) $*.tex
	cd pub ; $(PBIB) $*
	touch $@

pub/%.pdf: pub/%.tex pub/%.toc  pub
	@echo : Making $@
	cd pub ; $(PDFLATEX) $*.tex
	cd pub ; $(PDFLATEX) $*.tex
	touch $@

pub/$(NAME).toc: $(addprefix pub/,$(SOURCES)) pub
	@echo : Making $@
	cd pub ; $(PTEX) $(NAME).tex
	touch $@

# ----
# Helpers
# ----

# Pandoc helpers

%.doc: %.md
	pandoc $< -o $@

%.rtf: %.md
	pandoc $< -o $@

%.pdf: %.md
	pandoc --latex-engine=xelatex -V mainfont='Anonymous Pro' -V mathfont='XITS' $< -o $@

# Printing helpers
$(NAME)-updown.pdf: $(NAME).pdf
	pdftk A="$<" shuffle Aodd Aevensouth output "$@"
	touch $@
